# Generated by Django 4.2.11 on 2024-04-08 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('File_Ninja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(default='No offer name available', max_length=100)),
                ('cost', models.FloatField(default=0)),
                ('validity', models.IntegerField(default=30)),
                ('description', models.TextField(default='No description available')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('profile_picture', models.URLField(null=True)),
                ('locale', models.CharField(max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('number', models.CharField(max_length=10, null=True)),
                ('is_premium', models.CharField(default='NO', max_length=3)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='File_Ninja.subscriptions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='payments_transection',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('payment_mode', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('Credit_Card_Number', models.CharField(max_length=16)),
                ('name_on_card', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='File_Ninja.subscriptions')),
            ],
        ),
        migrations.CreateModel(
            name='active_subscription_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='File_Ninja.subscriptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
