# Generated by Django 4.2.11 on 2024-04-08 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('File_Ninja', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_subscription_list',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='File_Ninja.payments_transection'),
        ),
    ]
