# Generated by Django 4.2.11 on 2024-04-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_Ninja', '0002_userprofile_dob_userprofile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_premium',
            field=models.CharField(default='NO', max_length=3),
        ),
    ]
