# Generated by Django 4.2.11 on 2024-04-08 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('File_Ninja', '0003_active_subscription_list_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments_transection',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
