# Generated by Django 4.2.11 on 2024-04-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_Ninja', '0003_userprofile_is_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_pack', models.CharField(default=29, max_length=100)),
                ('premium_pack', models.CharField(default=49, max_length=100)),
            ],
        ),
    ]
