# Generated by Django 4.2.11 on 2024-04-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_Ninja', '0004_payments_transection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='active_subscription_list',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments_transection',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
