# Generated by Django 4.2.11 on 2024-04-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_Ninja', '0005_active_subscription_list_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active_subscription_list',
            name='id',
        ),
        migrations.AlterField(
            model_name='active_subscription_list',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
