# Generated by Django 4.2.11 on 2024-04-09 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('File_Ninja', '0007_alter_payments_transection_credit_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subscription',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='File_Ninja.subscriptions'),
        ),
    ]
